language: scala

jdk:
  - openjdk8

before_install:
  - git fetch --tags

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - rvm use 2.6.0 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 4.0.0

stages:
  - name: test
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork

jobs:
  include:
    # stage="test" if no stage is specified
    - env: TEST="build"
      script: sbt +compile +test docs/paradox coverageReport
    # run ci-release only if previous stages passed
    - stage: release
      script: sbt ci-release

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
