language: scala

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable

jdk:
  - openjdk8
  - openjdk11

script:
  - sbt ++2.11.12 test
  - sbt ++2.13.0 testsJVM/test testsJS/test
  - sbt ++2.12.9  coverage test docs/tut coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
